### ISSUE TITLE
Error on getting tower worth

### ISSUE THREAD

**Issue by AyalCiobotaru** [doombubbles/sacrifice-helper#3]
Thanks for this mod! This is exactly what I've been looking for!
Getting this error as soon as I click on a Sun Avatar or Sun Temple:

```
[22:35:09.622] [Il2CppInterop] During invoking native->managed trampoline
[22:35:09.624] [BloonsTD6_Mod_Helper] System.TypeLoadException: Could not load type 'Il2CppAssets.Scripts.Simulation.Objects.CommonBehaviorProxy' from assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SacrificeHelper.Utils.GetTowerSetWorth(String towerSet, Tower tower)
   at SacrificeHelper.Utils.<>c__DisplayClass6_0.<GetTowerWorths>b__1(String s) in /home/runner/work/sacrifice-helper/sacrifice-helper/SacrificeHelper/Utils.cs:line 100
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at SacrificeHelper.Utils.GetTowerWorths(Tower tower) in /home/runner/work/sacrifice-helper/sacrifice-helper/SacrificeHelper/Utils.cs:line 100
   at SacrificeHelper.SacrificeHelperUI.UpdateTempleStuff(TowerToSimulation tower) in /home/runner/work/sacrifice-helper/sacrifice-helper/SacrificeHelper/SacrificeHelperUI.cs:line 133
   at SacrificeHelper.SacrificeHelperUI.TowerInfoChanged() in /home/runner/work/sacrifice-helper/sacrifice-helper/SacrificeHelper/SacrificeHelperUI.cs:line 104
   at SacrificeHelper.SacrificeHelperMod.TowerSelectionMenu_UpdateTower.Postfix(TowerSelectionMenu __instance) in /home/runner/work/sacrifice-helper/sacrifice-helper/SacrificeHelper/SacrificeHelperMod.cs:line 198
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.InGame.TowerSelectionMenu.TowerSelectionMenu::UpdateTower>(TowerSelectionMenu this)
   at (il2cpp -> managed) UpdateTower(IntPtr , Il2CppMethodInfo* )
```

Am I missing `Assembly-CSharp`? Any ideas?

**Comment by AyalCiobotaru** [comment]
Downloaded VS 2022 and ran it locally, seems to be working fine now.
